name: Check and test the source code
on:
  push:

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: tideplatform/security-flutter-sbom
          path: master
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
            flutter-version: '3.0.5'
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test
